version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: course-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  course-finder:
    build: .
    container_name: course-finder-container
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin@123@course-postgres:5432/mydb?schema=public"
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy &&  npx prisma db seed && npm start"

volumes:
  postgres_data: